version: '3'

services:

  front-side:
    container_name: music-search
    build:
      context: .
      dockerfile: Dockerfile
    restart: always    
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development    
      
  